### ISSUE TITLE
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "UCNV_FROM_U_CALLBACK_STOP_70" referenced by.... /libFoundation.so"...

### ISSUE THREAD

**Issue by johnburkey** [finagolfin/swift-android-sdk#53] opened 2022-06-22 20:55 UTC
trying to get your sdk to run on droid.

Have you seen this?  The symbol is an ICU error handling symbol

**Comment by vinceplusplus** [comment] 2022-06-29 10:01
encountered the same issue, it could be worked around with an advance library load
```kotlin
System.loadLibrary("icuuc")
```
you will then encounter another one but similar
```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "ucal_setMillis_70" referenced by ".../libFoundation.so"...
```
again, it could be worked around with another advance library load
```kotlin
System.loadLibrary("icui18n")
```

when using `readelf`, the dynamic section for `libFoundation.so` seems to look fine
```
  0x000000000000001d (RUNPATH)      Library runpath: [$ORIGIN/../..:$ORIGIN]
  0x0000000000000001 (NEEDED)       Shared library: [libswiftDispatch.so]
  0x0000000000000001 (NEEDED)       Shared library: [libicuuc.so]
  0x0000000000000001 (NEEDED)       Shared library: [libicui18n.so]
  0x0000000000000001 (NEEDED)       Shared library: [libicudata.so]
  0x0000000000000001 (NEEDED)       Shared library: [libdispatch.so]
...
```

Vlad's toolchain doesn't have this problem though

**Comment by buttaface** [comment] 2022-06-29 10:46
@vinceplusplus, I've never tried loading multiple native shared libraries for an Android app, I would always just bundle everything together in one shared library when not using Swift. Is it expected to have a `loadLibrary()` call for each Android native dependency?

**Comment by vinceplusplus** [comment] 2022-06-29 11:46
@buttaface are you referring to having just one big and main `.so` library with all other dependencies statically linked into it?   yes, it could be preferred as with static linking, parts that aren't actually in use could be removed from the final binary and it should be faster as well. so for swift standard libraries, it could be something like `--static-swift-stdlib` or `-Xswiftc -static-stdlib`, but somehow it isn't quite working now (with your sdk and Vlad's one), it comes with something like this
```
Fatal error: .../swift-5.6-android-aarch64-24-sdk/usr/lib/swift/android/static-stdlib-args.lnk not found
```
on linux, `-Xswiftc -static-stdlib` works though

as for `loadLibrary()`, it shouldn't be the case, it should be able to have just one `loadLibrary()` for the main binary then it should load the rest if need be. so with Vlad's one, i do not need the following
```kotlin
System.loadLibrary("icuuc")
System.loadLibrary("icui18n")
```

also, in the official [hello-libs](https://github.com/android/ndk-samples/tree/main/hello-libs) sample, the main shared library links with one static library and one shared library, but there is just one `System.loadLibrary()` call

but as an aside, i can't get using `cmake` to work, so far it's just the old school `jniLibs` way

**Comment by vinceplusplus** [comment] 2022-06-30 08:41
> That's weird, it should be looking in usr/lib/swift_static/android instead, which I do build and provide and that file is in there. Could be a bug in the Swift compiler when cross-compiling?

could be. also, to contrast the structure in the linux release (5.6.1), the icu files are placed in `usr/lib/swift/linux` and `usr/lib/swift_static/linux` whereas those files in this sdk are placed in `usr/lib`. then `usr/lib/swift_static/android` in this sdk doesn't have like `libswiftCore.a` whereas it does in the linux release. the `libFoundation.a` in `usr/lib/swift_static/android` is bigger though (are some of the missing files linked into `libFoundation.a`?)

> Interesting, that's why I reopened this. Does Vlad name those libraries differently? Can you try that and see if it makes a difference? Something like mv libicuuc.so libicuucswift.so; patchelf --replace-needed libicuuc.so libicuucswift.so libFoundation.so for each dependency should do it. If you can track down why it doesn't work, I will add that info to my doc.

yes, Vlad names those files with a `swift` suffix and it is also the way those are named in the linux release. tried `patchelf` on macOS and utm arm64 ubuntu, no luck. on macOS, it doesn't allow to patch `libFoundation.so` (is fine for `libicuuc.so` and `libicui18n.so`) and comes back with
```
patchelf: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections
```
while it works fine with utm arm64 ubuntu with the files, during runtime, it comes back with
```
java.lang.UnsatisfiedLinkError: dlopen failed: ".../lib/arm64/libFoundation.so" loaded phdr 0x71e86c4040 not in loadable segment
```

> Meaning when using CMake's Swift support or Android support to compile your Swift code with my Android SDK or something else?

turned out it was caused by the lack of a soname of the package binary produced by the sdk and a specific behavior of android cmake under this situation (using somewhat a full path in the absence of a soname), it was discussed here in detail, https://github.com/android/ndk-samples/issues/669. again, the `jniLibs` way doesn't have this problem though

**Comment by buttaface** [comment] 2022-07-02 16:40
> in the linux release (5.6.1), the icu files are placed in usr/lib/swift/linux

Yes, I put all the prebuilt Android libraries from Termux packages in `usr/lib/`, with only the libraries built by this Swift repo in `usr/lib/swift/`.

> then usr/lib/swift_static/android in this sdk doesn't have like libswiftCore.a whereas it does in the linux release

Huh, I missed that, looks like I've been missing that static stdlib since my first SDK release. Good catch, I will add it to the next release.

> while it works fine with utm arm64 ubuntu with the files, during runtime, it comes back with `java.lang.UnsatisfiedLinkError: dlopen failed:`

Oh, I missed one step, you will also need to rename each soname: `patchelf --set-soname libicuucswift.so libicuucswift.so`, maybe that's why.

**Comment by vinceplusplus** [comment] 2022-07-03 16:32
> Oh, I missed one step, you will also need to rename each soname: patchelf --set-soname libicuucswift.so libicuucswift.so, maybe that's why.

tried, no luck. perhaps, it really does have something to do with `patchelf: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections`, and that `libFoundation.so` is a little bit different than the rest of the normal c libs

today, i tried to use `URLSession`, i followed the instructions to get packages from `Termux`, patching `rpath`, dropping `soversion`, patching `needed`, etc. finally, it's working. and i used only the `patchelf` on my mac, so the tool should be working. so it is this `patchelf` complained "PT_NOTE" but not the linux one, guess that it's somehow genuine and that `libFoundation.so` could be at fault in this regard

**Comment by buttaface** [comment] 2022-07-05 14:30
> that libFoundation.so is a little bit different than the rest of the normal c libs

Could be something like that, I plan to start trying out Swift with JNI in a GUI Android app next, will let you know what I find.

> today, i tried to use URLSession, i followed the instructions to get packages from Termux, patching rpath, dropping soversion, patching needed, etc. finally, it's working.

Glad to hear that.

Closing this now as John wrote me that everything is working for him now.

**Comment by buttaface** [comment] 2022-09-06 07:51
@vinceplusplus, finally put out a new 5.6.3 SDK release with the static stdlib included, let me know if it works for you.

**Comment by adrianjagielak** [comment] 2023-10-05 22:06
@finagolfin I came across a similar error in the recently released swift-android-sdk 5.9.

I'm compiling a Swift package (which imports Foundation) as a dynamic library (`type: .dynamic` in Package.swift).

On 5.8 I don't get any errors when trying to load it in my app.

On 5.9 with the same configuration I'm getting
```
dlopen failed: cannot locate symbol "UCNV_FROM_U_CALLBACK_STOP_73" referenced by "/data/app/{redacted}/lib/arm64/libFoundation.so"...
```
(which is different from the standard errors when a library can't find a linked library, i.e. "`dlopen failed: library "libfoo.so" not found`")

**Comment by finagolfin** [comment] 2023-10-06 04:21
Hmm, are you including the `libicu*so` libraries from the SDK in your app? The SDK for Swift 5.9 ships with libicu 73, so you may see this error if you're shipping an older libicu, say from the Swift 5.8 SDK.

**Comment by adrianjagielak** [comment] 2023-10-06 10:47
@finagolfin I am including the correct `libicudata.so`, `libicui18n.so`, and `libicuuc.so`. I can even see that the `UCNV_FROM_U_CALLBACK_STOP_73` symbol exists in the `libicuuc.so` (`strings libicuuc.so | grep UCNV_FROM_U_CALLBACK_STOP_73`), I don't know why it's not working.

I also attempted to manually load `libicudata`, `libicui18n`, and `libicuuc` before trying to load a library that depends on libFoundation, but to no avail.

**Comment by adrianjagielak** [comment] 2023-10-06 11:12
I've just tried the develop 5.10 build from Actions and it gives me the same `cannot locate symbol "UCNV_FROM_U_CALLBACK_STOP_73"` error.

**Comment by finagolfin** [comment] 2023-10-06 14:31
Are you changing the rpaths for these libraries with `patchelf` before putting them in an app? If so, can you try it with `patchelf` on linux, as mentioned above?

**Comment by adrianjagielak** [comment] 2023-10-06 15:56
Okay, patching the libraries using `patchelf` has fixed this error, so apparently the libFoundation has tried to load system-provided icu libraries instead of the local ones before.

Only libicuuc.so and libicui18n.so patching is needed for now but I've patched every icu library just to be sure:

```sh
mv libicudata.so libicudataswift.so
mv libicui18n.so libicui18nswift.so
mv libicuuc.so libicuucswift.so

patchelf --replace-needed libicudata.so libicudataswift.so libFoundation.so
patchelf --replace-needed libicudata.so libicudataswift.so libicui18nswift.so
patchelf --replace-needed libicudata.so libicudataswift.so libicuucswift.so

patchelf --replace-needed libicui18n.so libicui18nswift.so libFoundation.so
patchelf --replace-needed libicui18n.so libicui18nswift.so libicudataswift.so
patchelf --replace-needed libicui18n.so libicui18nswift.so libicuucswift.so

patchelf --replace-needed libicuuc.so libicuucswift.so libFoundation.so
patchelf --replace-needed libicuuc.so libicuucswift.so libicudataswift.so
patchelf --replace-needed libicuuc.so libicuucswift.so libicui18nswift.so

patchelf --set-soname libicudataswift.so libicudataswift.so
patchelf --set-soname libicui18nswift.so libicui18nswift.so
patchelf --set-soname libicuucswift.so libicuucswift.so     
```

I don't know why this patching is needed only for 5.9+ and not needed for 5.8 though.

It should probably be patched when building the SDK itself like in Vlad's toolchain ("libicuucswift.so", "libicui18nswift.so", and "libicudataswift.so").

**Comment by finagolfin** [comment] 2023-10-07 05:32
> apparently the libFoundation has tried to load system-provided icu libraries instead of the local ones before.

I highly doubt this, as the system libraries are not available normally and I believe require special patching to access. On my Android 13 phone, I don't even see a libicu installed in `/system/lib64/`.

> I don't know why this patching is needed only for 5.9+ and not needed for 5.8 though.

> It should probably be patched when building the SDK itself like in Vlad's toolchain ("libicuucswift.so", "libicui18nswift.so", and "libicudataswift.so").

He did that because the Swift toolchain provides an older libicu that it renames, whereas I use the newer prebuilt libicu packages from the Termux app.

You didn't answer my question about whether you were modifying the rpaths alone for these shared libraries in some way before. I see no difference between the way the Swift 5.8 SDK and now 5.9 provision all these libraries, so I suspect it is some change on your end triggering this.

**Comment by finagolfin** [comment] 2023-10-16 00:49
Closing since no response.

**Closed by finagolfin** 2023-10-16 00:49 UTC
